cryptonative-ch/aqua-interface

.gitignore, src/utils/wallets.ts, src/views/Auction/components/BidList.tsx
- Code formatting
- Add `.env` to `.gitignore`
- Fix ESLint wanrings (there are more)
=> Minor changes to code

.eslintrc.js
https://stackoverflow.com/a/64024916/2151050
=> Fix no-use-define

src/mesa/auction.ts, src/mesa/price.ts, src/views/Auction/index.tsx, src/views/Auctions/components/AuctionFinalPrice.tsx, src/views/Auctions/components/AuctionStatus.tsx, src/views/Auctions/index.tsx, src/views/Simulation/index.tsx
- Price calculation
- Auction functions
=> Split Mesa functions

src/views/Auction/components/BidList.tsx, src/views/Auction/components/Graph.tsx
- Highlight the user's bid in the bid list and chart.
- Improvement Chart performance by using `useRef` hook.
=> UI and UX improvements

src/views/Auction/components/PlaceBidForm.tsx
This PR to address the issue with outdated state issue in the form in `validateForm` function
=> Fix state issues in PlaceBidForm

src/views/Auction/components/BidList.tsx, src/views/Auction/index.tsx, src/views/Simulation/index.tsx
- Deconstruct `userAddress`
- Import missing components to Auction view
=> Latest fixes

src/styles/theme.ts
=> Change radii base

src/data/auction.ts, src/mesa/auction.ts, src/utils/date.ts, src/views/Auction/components/PlaceBidForm.tsx, src/views/Auction/components/Timer.tsx, src/views/Auction/index.tsx, src/views/Simulation/index.tsx
Updated the timer component such that it changes states upon the auction status changing. 
Updated the placebidform component such that the button disables upon auction status changing.
=> Disable bidding

src/components/ErrorMessage/index.tsx, src/components/Link/index.tsx, src/router/index.tsx
- Partially implements #55 on the route
- Adds `ErrorMessage` component for handling 
- Moves `Link.tsx` to `src/components/index.tsx` as per new style guide drafted in #60
=> /simulation to /demo and some more improvments

package.json, src/App.tsx, src/constants/index.ts, src/contexts/index.tsx, src/router/index.tsx
---
title: 'Geo blocking'
labels: 'enhancement, help wanted, investor frontend, question'
assignees: 'light-fury'
---
UN-Sanction list, see how this is done by uniswap interface.
- Call the ipapi to get the current country of the browser
- Check with the UN_SANCTION list
- Remove all the routes if the browser is from one of those countries
https://github.com/cryptonative-ch/mesa-interface/issues/1
I tested this on Chrome & Safari with MacOS.
=> add geoblocking feature with ipapi service

.eslintrc.js, .github/workflows/github_action.yml, package.json, src/App.tsx, src/contexts/index.tsx, src/hooks/useAuctions.ts, src/hooks/useModal.tsx, src/mesa/price.ts, src/views/Auction/components/BidList.tsx, src/views/Auction/components/Header.tsx, src/views/Auction/components/PlaceBidForm.tsx, src/views/Auction/index.tsx, src/views/Auctions/components/AuctionSummaryCard.tsx, src/views/Simulation/index.tsx, tsconfig.json
---
title: 'GitHub action for CI/CD'
labels: 'enhancement, nice to have'
assignees: 'light-fury'
---
CI/CD to resolve the build failures and possible accidents on test/live servers
https://github.com/cryptonative-ch/mesa-interface/issues/77
Tested this with github_action branch
=> GitHub action

.eslintrc.js, package.json, src/data/initialbids.ts, src/redux/BidData.ts, src/redux/store.ts, src/views/Auction/components/BarChart.tsx, src/views/Auction/components/BidList.tsx, src/views/Auction/index.tsx, src/views/Simulation/index.tsx
---
title: ''
labels: ''
assignees: ''
---
This provides a fix to "simulating" the cancellation of bids.
* Fixed the cancel button such that it removes bids
* Fixes #79 
* Created redux component for the bid data
* moved initial bids
* bids no longer uses state but redux instead to manage it
* Fixes #56  
* Fixes #71 
* The bids already contains a column for dai price per token and are also sorted according to the `lowerClearingPrice` function. Bids are also colour coded according to activity status
PS. I will be testing all my components written by the next PR. I just want to do all the testing in one go
=> Cancelbutton

src/router/index.tsx
Fixed to lowercase in routing -> fixed
Path should only have small cap
Manual Test:
http://localhost:3000/auctions/fixed/0x142
=>  Fixed to lowercase in routing -> fixed

public/locales/en/translation.json, src/components/Footer/index.tsx, src/router/index.tsx
Link in footer to outside and to inside pages (will follow)
- :-( All new and existing tests passed.
=>  Links in Footer

package.json, src/App.tsx, src/components/Header/index.tsx, src/connectors/CustomNetworkConnector.ts, src/connectors/index.ts, src/views/Sale/FixedPrice.tsx, src/views/Sale/components/TokenFooter/index.spec.tsx, src/views/Sale/components/TokenFooter/index.tsx, src/views/Sale/index.tsx, src/views/Sales/index.tsx, src/views/Static/components/StaticContent/index.spec.tsx, src/views/Static/components/StaticContent/index.tsx, src/views/Static/index.tsx
- `cryptowalletconnector` and `use-wallet` add extra abstractions; they were removed in favor of using `@web3-react/core`.
- Removed repeated code; DRY principle
- Self-contained `Header` component (there is still some chore to clean up the social links for mobile view)
- Added some code from Swapr.
This PR is a part of a bigger feature. 
Manual testing.
=> Add Wallet Connect for xDAI

src/App.tsx, src/contexts/index.tsx
=> Reduce code for UN sanction list

src/connectors/index.ts, src/constants/index.ts, src/providers/index.ts, src/views/Sale/components/TokenFooter/index.tsx
- Add `CHAIN_ID` enum for Rinkeby, XDAI and Mainnet.
- Rename `INFURA_API_KEY` to `INFURA_PROJECT_ID`.
- Update imported constant where applicable.
n/a
=> Update constant names

src/router/index.tsx, src/views/Sale/FixedPrice.tsx, src/views/Sale/index.tsx, src/views/Sales/index.tsx, src/views/Static/index.tsx
- Remove `Header` props and hooks
- Drop `getRandomWallet` from views
- Reorganize grouped imports to follow project guideline
=> Remove unused code

package.json, src/App.tsx, src/hooks/useMesa.ts, src/mesa/index.ts
This PR installs `@dxdao/mesa@0.1.2` in the interface.
- Add `useMesa` hook
- Add configuration for xDAI (default), Rinkeby and local development (
- Configure `MesaContext` and its Provider
Manual testing.
=> Install MesaJS

src/hooks/useSale.ts, src/hooks/useSales.ts
Adds `useSales` and `useSale` hooks
These hooks refactor the using `useSelector` and `useDispatch` hooks in Sales views. These hooks were dropped during the development. Now they are crucial.
=> Add useSales and useSale hooks

public/locales/en/translation.json, src/blockchain/index.ts, src/components/Title/index.tsx, src/subgraph/index.ts, src/views/NotFound/index.tsx, src/views/Sale/FixedPrice.tsx, src/views/Sale/components/PlaceBidForm/index.tsx, src/views/Sale/index.tsx, src/views/Sales/index.tsx
=> created 404 page

README.md, package.json, src/router/index.tsx, src/views/Sale/index.tsx
Changelog
- Add `useSale` to handle sale type in `Sale/index.ts`
- Remove `fixed` from routing table
Misc:
- Use args for (~~`server`~~ `subgraph-server`) to run on all OS.
Manual testing. This might break tests.
=> Refactor Sales into FixedPriceSale and FairSale

src/blockchain/index.ts, src/interfaces/Sale.ts, src/redux/bids/index.ts, src/subgraph/SaleBids/index.ts, src/subgraph/index.ts, src/utils/Defaults/index.tsx, src/views/Sale/components/Timer/index.tsx, src/views/Sale/index.tsx, src/views/Sales/components/SaleAmount/index.tsx, src/views/Sales/components/SaleFinalPrice/index.tsx, src/views/Sales/components/SaleSummaryCard/index.tsx
Changelog
- `saleType` to `SaleType`. Refer to Contribution Guideline for naming interfaces.
- Reflect the change wherever this type is used.
In a future PR, use an enum for this. It is more robust for comparions.
=> Chore: Change saleType to SaleType

graphql-schema.json, package.json, src/subgraph/__generated__/GetFixedPriceSalePurchasesBySaleId.ts, src/subgraph/__generated__/GetSingleSale.ts, src/subgraph/__generated__/fairSaleResults.ts, src/subgraph/__generated__/fixedPriceSalePurchaseResults.ts, src/subgraph/__generated__/fixedPriceSaleResults.ts, src/subgraph/__generated__/tokenResults.ts, src/subgraph/attributes.ts, src/subgraph/queries.ts
Changelog:
- Add `apollo-codegen` to scripts
- Update query interfaces
- Add source GraphQL schema from currently deployed subgraph
- Reduce fields into constants for composability
=> Amend Sales Subgraph Queries and Interfaces

src/hooks/useApprovalCallback.ts, src/hooks/useFixedPriceSalePurchasesQuery.ts, src/hooks/useSaleQuery.ts, src/hooks/useTokenAllowance.ts, src/hooks/useTokenContract.ts, src/utils/index.ts
Fetches all purchases from a`FixedPriceSale`
Connects to a ERC20 contract, accepts a contract address and signer/provider
Fetches the token allowance value for a address
Forked from Uniswap, 
Fetches `FixedPriceSale` from the subgraph
Fetches`FairSale` from the subgraph
Manual testing
=> Add sale and contract hooks 

src/views/Sale/components/PurchaseTokensForm/index.tsx
Chores for future PR
- Remove logging and extra components from previous commits
- Add remaining validation logic
- `tokenAmount > sale.allocationMax` = invalid input
- Add UI for successful purchases
=> Add `PurchaseTokensForm` for `FixedPriceSale` 

src/App.tsx, src/constants/index.ts
- Disable the Terms of Sale popup displayed on initial app open.
- Introduce a constant so the popup can be enabled later if needed.
#191
Tested locally using start-xdai and with incognito mode to test cookie handling.
=> Introduce constant to toggle Terms of Sale popup.

.eslintrc.js, src/views/Sale/FairSale.tsx, src/views/Sale/components/PlaceBidForm/index.tsx, src/views/Sale/components/PurchaseTokensForm/index.tsx, src/views/Sales/components/SaleSummaryCard/index.tsx, src/views/Token/index.tsx
Testing to fix build error in github actions ci check
#201
=> fixing eslint issues

src/blockchain/index.ts, src/subgraph/Sales/index.ts, src/subgraph/index.spec.ts, src/views/Sale/components/HeaderControl/index.spec.tsx, src/views/Sale/components/Timer/index.spec.tsx
Remove unused imports that were triggering lint warnings.
Running the lint command was spitting out a lot of warnings, making it harder to identify lint issues introduced by new code changes.
Tested locally after changes with start-xdai command.
=> Remove unused imports from code.

src/components/Container/index.tsx, src/components/Grid/index.ts
Added margin bottom and fixed height value.
#230
Added multiple cards to ensure no overlapping issues
=> fixed overlap issue

src/views/Sale/saleInfo.mock.json
- Add a mock JSON file with sale information data structure.
#233
=> Add mock json with sale information data structure.

public/locales/en/translation.json, src/components/Header/index.tsx, src/views/Sale/FixedPrice.tsx, src/views/Sale/components/BadgeCard/index.spec.tsx, src/views/Sale/components/BadgeCard/index.tsx, src/views/Sale/components/SaleHeader/index.spec.tsx, src/views/Sale/components/SaleHeader/index.tsx, src/views/Sale/components/TokenFooter/index.tsx, src/views/Sales/components/SaleSummaryCard/index.spec.tsx, src/views/Sales/components/SaleSummaryCard/index.tsx
Small UI changes
- Added correct sale token address and link to block explorer
- Removed 'Initial sale'
- Changed 'private' to 'public'
- Added correct max allocation to purchase form
- Below shows different options for making network banner clearer
#232
=> small ui changes

src/assets/index.ts, src/hooks/useIpfsFile.ts, src/interfaces/Sale.ts, src/utils/Defaults/index.tsx, src/views/Sale/FixedPrice.tsx, src/views/Sale/components/TokenFooter/index.spec.tsx, src/views/Sale/components/TokenFooter/index.tsx
- Load Sale Details mock JSON locally and render content in `TokenFooter` dynamically.
- Update unit tests for `TokenFooter`.
#235 
- Tested locally using start-xdai.
- Unit test added to check if content is being loaded.
- Existing unit tests have been updated.
=> Load and show sale details dynamically.

src/constants/index.ts, src/hooks/useIpfsFile.ts, src/views/Sale/FixedPrice.tsx
- Adds implementation to load sale info from IPFS.
#237 
Tested locally using start-xdai and mock IPFS json files.
=> Load sale info JSON from IPFS.

src/App.tsx, src/components/Footer/style.tsx, src/components/Grid/index.ts, src/views/Sale/FairSale.tsx, src/views/Sale/FixedPrice.tsx, src/views/Sale/index.tsx, src/views/Sales/index.tsx, src/views/Static/index.tsx, src/views/Token/index.tsx
There were some remaining issues with the footer bar so I have fixed this again for all pages.
Also @martinkrung previously mentioned that the header was being re-rendered when navigating pages so I have moved the component up to the root level so it is always rendered and doesn't get re-rendered.
#256
=> fixing footer issues and refreshing header bar issue

src/views/Sale/components/SelfBidList/index.tsx
Round the token purchase amount to 2 nearest decimals.
#254 
Tested locally with start-xdai, making a bid.
=> Round the token purchase amount to 2 decimals instead of closest integer.

package.json, src/components/InfoTooltip/index.tsx, src/components/Tooltip/index.tsx, src/views/Sale/components/HeaderControl/index.tsx
- Add generic `Tooltip` component.
- Add `InfoTooltip` component based on the generic tooltip implementation.
- Implement an information tooltip for the Min. Threshold value.
#264 
Tested locally using start-xdai.
=> Add information tooltip implementation.

package.json, public/locales/en/translation.json, src/App.tsx, src/components/Container/index.tsx, src/components/Header/index.tsx, src/hooks/useApprovalCallback.ts, src/hooks/useBids.ts, src/hooks/useChain.ts, src/hooks/useSale.ts, src/hooks/useSales.ts, src/hooks/useTokenBalance.ts, src/hooks/useTokenClaim.ts, src/views/Sale/components/HeaderClaim/index.tsx, src/views/Sale/components/PurchaseTokensForm/index.tsx, src/views/Token/index.tsx
I have added a package that allows us to create toast popup notifications anywhere in the UI.
Toast messages have been added as translations
I went through and added these as error toasts to most catch conditions. (toast.error)
I also added success notifications for claiming, withdrawing, purchasing and approving (toast.success).
To make it work for approvals I had to fix how pending was being set which fixed another bug, so the loading spinner should stay until fully approved now.
There are success, error, dark, info, warning and default toast types available.
Global toast settings can be changed in app.tsx including the auto close time (currently set to 10 seconds).
Package used: [React-toastify](https://www.npmjs.com/package/react-toastify)
#263 
Locally by testing known errors and …
=> Toast notifications

public/locales/en/translation.json, src/components/InfoTooltip/index.tsx, src/components/Tooltip/index.tsx, src/views/Sale/FixedPrice.tsx, src/views/Sale/components/HeaderControl/index.tsx, src/views/Sale/components/HeaderItem/index.tsx
- Fix a bug that was causing issues with rendering multiple tooltips in the same page.
- Add more tooltips to the sale page.
- Use the translations file to load tooltip text.
#284 
Locally tested with start-xdai.
=> Tooltip improvements and additional tooltips on sale page.

src/hooks/useApprovalCallback.ts, src/utils/Defaults/index.tsx, src/views/Sale/components/PurchaseTokensForm/index.tsx
This issue is caused by javascript not being accurate when dealing with small numbers in this context.
The values of minAllocation and tokenPrice etc are all normal when printed before calculation and only after multiplying does the accuracy error occur.
The fix is relatively simple, using a custom function similar to toFixed. Apparently, there are small issues with toFixed for this use and so better to use this new method.
From testing, it appears to work well.
This will also be less of an issue once we move the UI to denominate in tokenIn since the user will determine what gets sent to the contract in the buy function and the SC will do the calculation when claiming tokens. (this will remain but only be used to inform the user of values)
[Fix from …
=> Fixing accuracy issue

src/views/Sale/index.tsx
Use `tokenOut` for the page title, instead of `tokenIn`.
#259 
Tested locally using start-xdai.
=> Use tokenOut for the page title.

src/views/Sale/components/PurchaseTokensForm/index.tsx
Remove browser validation from the token purchase form input field. We have custom validations written, so the default browser validation is unnecessary.
#299 
Tested locally using start-xdai.
=> Remove browser validation from purchase form input.

src/views/Sale/components/PurchaseTokensForm/index.tsx
Fix token purchase rejection toast notifications. Previously it was showing both success and failure toast messages on rejection.
#298 
Tested locally using start-xdai.
=> Fix token purchase rejection toast notifications.

src/views/Sale/components/PurchaseTokensForm/index.tsx
Some browsers still have validations for the token value input after #302. This disables all browser validations in the form.
#299 
Tested locally on start-xdai, using Webkit (Chrome / Edge) and Gecko (Firefox) browsers.
=> Disable browser validations from purchase form.

public/robots.txt
Block search indexing in robots.txt. Currently it is set to allow indexing access.
Fixes #294 
Checked whether the file is being served correctly locally.
=> Block search indexing in robots.txt

src/utils/Defaults/index.tsx, src/views/Sale/FixedPrice.tsx, src/views/Sale/components/PurchaseTokensForm/index.tsx, src/views/Sale/components/SelfBidList/index.tsx, src/views/Sales/components/SaleFinalPrice/index.tsx
This branch is a start to change fixed price sale to the new SC fixed price sale.
Currently it does not change variable names / method names but this can be done once the new version is finished and subgraph changes also finished.
It currently just:
- Changes all denominations to use tokenIn
- Adds converter to change tokenPrice to more understandable format (cost for 1 tokenOut)
Making this a method will allow for easier changes in the future if we alter the SC to this format
I am still going through the SC and UI to find changes I have missed.
Will also require proper testing once complete.
#290
=> New SC changes in UI

package.json, src/App.tsx, src/assets/index.ts, src/components/Header/index.tsx, src/components/Modal/index.tsx, src/components/Web3ProvidersModal/index.tsx, src/components/Web3ProvidersModal/style.tsx, src/connectors/index.ts, src/contexts/index.tsx, src/providers/web3.tsx
- Implement support for multiple wallet providers.
- Add WalletConnect support.
- Add support for disconnecting connected wallet.
- Add wallet provider selection modal.
The following would be addressed in separate PRs:
- Eager re-connection to previously connected wallet on page refresh
- Better UI for wallet disconnection.
Fixes #275.
Tested locally using start-xdai. WalletConnect functionality has been tested with MetaMask Mobile wallet.
=> Refactor code to support multiple wallet providers

src/providers/web3.tsx
Automatically reconnect to Injected Web3 Provider (MetaMask) when the user returns to the site / refreshes the page.
Fixes #330.
=> Eager-reconnect to injected wallet.

src/providers/web3.tsx
Handle  unsupported network error in eager connect.
Eager re-connection functionality throws an error and crashes the app when the injected wallet is connected to an unsupported network.
=> handle error in eager-connect when on an unsupported network.

CONTRIBUTING.md, README.md, public/locales/en/translation.json, src/components/Footer/index.tsx, src/components/Header/index.tsx, src/constants/index.ts, src/views/Sale/saleInfo.mock.json, src/views/Static/components/StaticContent/index.spec.tsx, src/views/Static/components/StaticContent/index.tsx, src/views/Static/components/StaticHeader/index.spec.tsx, src/views/Static/components/StaticHeader/index.tsx
- Change Mesa to Aqua in UI elements.
- Update the Twitter links to the new URL.
Fixes #316 
=> Rename Mesa to Aqua in the UI.

src/subgraph/mock/index.ts, src/subgraph/mock/server.ts
Updated subgraph mocks to accommodate the latest changes to the subgraph as of https://github.com/cryptonative-ch/mesa-subgraph/commit/b42433e6d04f1cbb9741b1dbaabb044b6fcc1130.
Also ignores a couple of ESLint warnings that are unhelpful.
Closes #349.
Tested locally using `yarn subgraph-server`.
=> Add mocks for the latest subgraph changes.

public/404.html, public/index.html
This introduces a fix for single-page app routing when using GitHub pages, as described in https://github.com/rafgraph/spa-github-pages.
Fixes #370.
Tested locally, but will need a deployment to complete testing.
=> Fix SPA routing for GitHub Pages.

src/views/Sale/components/PurchaseTokensForm/index.tsx
Created a new function to get max price which considers the number of remaining tokens left in calculation. 
This is reused for displaying max as well as setting max.
So now if remaining tokens are less than maxAllocation it sets max to remaining tokens price 
#379
=> Fixing max for when remaining tokens less than maxAllocation

src/hooks/useTokenClaim.ts, src/redux/claims/index.ts, src/views/Token/components/SuccessfulClaim/index.tsx, src/views/Token/components/TokenClaim/index.tsx
=> fix: app crash on token claim

src/hooks/useBids.ts, src/hooks/useChain.ts, src/redux/bids/index.ts, src/views/Sale/FairSale.tsx
---
---
* Closes #386 
Tested Manually
=> fix: first purchase error

src/App.tsx, src/constants/index.ts, src/hooks/useAquaConfig.ts, src/views/Sale/FixedPrice.tsx, src/views/Sale/components/HeaderControl/index.tsx, src/views/Sale/components/PurchaseTokensForm/index.tsx, src/views/Sales/components/SaleAmount/index.tsx
- Removed the workarounds for displaying amount sold which was added due to a subgraph issue.
- Moved Aqua-js configs into a React hook.
- Added contract address overrides to the Aqua-js config.
Fixes #373.
Also partially addresses #383, although I will be cleaning up how we load the configs in a separate PR.
=> Remove workaround for amount sold.

graphql-schema.json, src/aqua/sale.ts, src/constants/index.ts, src/hooks/useIpfsFile.ts, src/subgraph/__generated__/GetAllSales.ts, src/subgraph/__generated__/GetFixedPriceSaleCommitmentsByUser.ts, src/subgraph/__generated__/GetSingleSale.ts, src/subgraph/__generated__/fairSaleResults.ts, src/subgraph/__generated__/fixedPriceSaleCommitments.ts, src/subgraph/__generated__/fixedPriceSaleResults.ts, src/subgraph/__generated__/fixedPriceSaleUsers.ts, src/subgraph/__generated__/globalTypes.ts, src/subgraph/__generated__/launchedTemplateResults.ts, src/subgraph/attributes.ts, src/views/Sale/FixedPrice.tsx, src/views/Sale/components/TokenFooter/index.tsx
- Updated the subgraph-schema.json file to use new subgraph schema from v0.1.1.
- Added regenerated typings for the new subgraph, and updated the code accordingly to get the UI up and running.
- Use real IPFS Metadata hash from actual sale instead of hardcoded mock value.
Closes #381 and #348.
=> Update subgraph schema and revisit IPFS integration

src/hooks/useReadBidEventFromBlockchain.ts
---
title: ''
labels: ''
assignees: ''
---
Removing unused variable
=> removing unused variable for build

.github/workflows/preview-deploy.yml
Update DNSLink TXT record on test domain when merging to `dev` branch.
The Aqua test domain at [aquadev.co](https://aquadev.co) uses [DNSLink](https://dnslink.io/) to point to the IPFS content hash of the Aqua UI. This is then used by the [Cloudflare IPFS gateway](https://cloudflare-ipfs.com) to serve IPFS content over a regular domain. 
This change will update the DNSLink record every time a new change is merged to `dev` branch, to make sure the domain always keeps pointing to the latest deployment.
1. Add the following DNS records to the domain
<table>
<tr>
<td>Type</td>
<td>Name</td>
<td>Content</td>
<td>TTL</td>
</tr>
<tr>
<td>CNAME</td>
<td>@</td>
<td>cloudflare-ipfs.com</td>
<td>60</td>
</tr>
<tr>
<td>TXT</td>
<td>_dnslink</td>
<td>dnslink=/ipfs/<content-hash-cid></td>
<td>60</td> …
=> Add test domain to IPFS deployment on the dev branch.

src/views/Sale/components/TokenFooter/index.tsx
- Add a button that will prompt the user to add the sale token to their wallet when clicked.
- This will be shown only to MetaMask users, as WalletConnect doesn't seem to support such functionlity.
Fixes #405.
=> Add button to add sale tokens to MetaMask.

src/views/Sales/index.tsx
---
title: ''
labels: ''
assignees: ''
---
* Closes #390
Manually tested
=> fix: inconsistent sales loading

public/locales/en/translation.json, src/constants/index.ts, src/hooks/useTokenClaim.ts, src/views/Sale/components/HeaderClaim/index.tsx, src/views/Sale/components/HeaderControl/index.spec.tsx, src/views/Sale/components/HeaderControl/index.tsx
Adding a modal and splitting up the action of closing a sale and claiming tokens.
Closes #404 
Tested both with a non closed sale and closed sale.
=> Added modal confirmation for closing sale

src/views/Sale/FixedPrice.tsx, src/views/Sale/components/SaleHeader/index.tsx
---
title: ''
labels: ''
assignees: ''
---
* Closes #399 
* There was an additional problem of the component not re-rendering when the Sale opens up so that has also been solved here.
* Moved useEffect component up from `SaleHeader` to `FixedPriceSaleView`
* Manually Tested
=> fix: FixedPriceSaleView not updating on sale change

src/hooks/useTokenClaim.ts, src/interfaces/Error.ts
---
title: ''
labels: ''
assignees: ''
---
* Closes #415 
* replaced old Error interface with `ProviderRpcError` interface
* Claim button state now remains in `UNCLAIMED` state rather than switch to `FAILED` state upon rejecting a transaaction via the wallet. 
Manually Tested
=> fix: RpcError on reject

src/components/Title/index.tsx, src/hooks/useSaleQuery.ts, src/views/NotFound/index.tsx
- Fix 404 page styles.
- Prevent the UI from crashing when the sale ID is invalid.
- Fix issues in Title component.
The sale page was crashing when the sale ID was incorrect.
=> Fix 404 page.

src/views/Sale/components/Timer/index.tsx
Show the year in sale pages and summary cards if its not the current year.
Fixes #424.
Tested locally using mock data.
=> Change time display behaviour.

src/contexts/index.tsx, src/views/Sale/FairSale.tsx, src/views/Sale/components/PlaceBidForm/index.spec.tsx, src/views/Sale/components/PlaceBidForm/index.tsx
- Refactor UI styles in the bid form to match fixed price sale.
- Remove unused `BidModalContext`.
- Update form validation behaviour.
Fixes #430.
Tested locally with mocks.
=> Refactor bid form.

package.json, src/constants/index.ts, src/hooks/useAquaConfig.ts
Updating to the newest aqua js version 0.1.4
Since the main and dev versions are currently equal I've gone with the main one to avoid changing when cutting mvp release.
On next SC upgrade the package should use dev version of aqua js which consumes dev version of aqua sc
=> Updated to aqua js version using aqua sc package

src/views/Sale/FairSale.tsx, src/views/Sale/components/PlaceBidForm/index.tsx
- Implement bidding functionality for fair sale.
- Also adds the token spending approval step before bidding.
A bunch of things have been left to be implemented at a later point. Please refer to the TODOs in the code.
Fixes #367. 
Tested locally. on Rinkeby deployment.
=> Implement bidding functionality for fair sale.
